import { Type } from 'class-transformer'
import {
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  MaxLength,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator'
import { MedicalRecordFieldType } from '../enums/medical-record-field-type.enum'
import { MedicalRecordFieldOptionDto } from './medical-record-field-option.dto'

export class MedicalRecordTemplateFieldDto {
  // Generated by the backend and immutable. Ignored on create; used on update to
  // preserve the key of existing fields. The client never sets it on create.
  @IsOptional()
  @IsString()
  key?: string

  @IsString()
  @MinLength(1)
  @MaxLength(120)
  label!: string

  @IsEnum(MedicalRecordFieldType)
  type!: MedicalRecordFieldType

  @IsBoolean()
  required!: boolean

  @IsInt()
  @Min(0)
  order!: number

  @IsOptional()
  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => MedicalRecordFieldOptionDto)
  options?: MedicalRecordFieldOptionDto[] | null

  @IsOptional()
  @IsString()
  @MaxLength(200)
  placeholder?: string | null

  @IsOptional()
  @IsString()
  @MaxLength(500)
  helpText?: string | null

  @IsBoolean()
  canonical!: boolean

  @IsOptional()
  @IsString()
  @MaxLength(60)
  canonicalKey?: string | null

  @IsOptional()
  @IsString()
  @MaxLength(60)
  sectionKey?: string | null
}
